plugins {
    id 'java'
}

group = 'com.github.arthurpicht'
version = '0.2.5'

java {
    withJavadocJar()
    withSourcesJar()
}

wrapper {
    gradleVersion = '9.2'
    distributionType = Wrapper.DistributionType.BIN
}

repositories {
    maven { url = "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases" }
    mavenCentral()
}

dependencies {
    implementation 'de.arthurpicht:ap-utils-core:1.23.0'
    implementation 'de.arthurpicht:ap-utils-io:0.0.25'
    implementation 'de.arthurpicht:ap-cli:0.1.4'
    implementation 'de.arthurpicht:ap-configuration:0.1.9'
    implementation 'de.arthurpicht:ap-console:0.4.4'

    implementation 'com.diogonunes:JColor:5.5.1'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.4'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.4'
}

test {
    useJUnitPlatform()
}

tasks.register('fatJar', Jar) {
    archiveClassifier = 'fat'
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest {
        attributes 'Main-Class': 'de.arthurpicht.meta.cli.Meta'
        attributes 'Version': project.property("version")
        attributes 'Build': new Date().format('yyyyMMddHHmmss')
    }

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}

tasks.register('tool') {
    dependsOn fatJar
}
